// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"database/sql"
	"time"
)

type Location struct {
	ID        int32
	Name      string
	Address   sql.NullString
	SiteUrl   sql.NullString
	Notes     sql.NullString
	CreatedAt sql.NullTime
	Latitude  sql.NullString
	Longitude sql.NullString
}

type Trip struct {
	ID             int32
	UserID         string
	Name           string
	Description    sql.NullString
	StartDate      time.Time
	EndDate        time.Time
	CreatedAt      sql.NullTime
	UpdatedAt      sql.NullTime
	StartPosition  sql.NullString
	FinishPosition sql.NullString
}

type TripLocation struct {
	TripID     int32
	LocationID int32
	Position   int32
}
